language: python
python:
  - "2.7"
install:
  - pip install -e .
  - pip install -r requirements.pip
  - pip install -r requirements-dev.pip
script:
  - py.test -v --pep8 --cov overalls overalls
after_success:
  - overalls --py --debug
